Employee/Employee/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('List.urls')),
]

Employee/List/urls.py
from django.urls import path
from List import views

app_name = 'List'

urlpatterns = [
    path('add', views.index, name="add"),
    path('show', views.show, name="show"),
    path('payment/<pk>/', views.change, name="change"),
    path('pdf', views.render_pdf_view, name="pdf"),

]

Employee/List/models.py
from django.db import models

from django.conf import settings
# Create your models here.

class Ta_Da(models.Model):
    date = models.DateField()
    name = models.CharField(max_length=50)
    travel_cost = models.FloatField()
    lunch_cost = models.FloatField()
    instrument_cost = models.FloatField()
    total_cost = models.FloatField()
    Paid = models.CharField(max_length=20)


   

class Employee(models.Model):
    name = models.CharField(max_length=50)
    

Employee/List/views.py
from django.shortcuts import render, HttpResponse,HttpResponseRedirect,get_object_or_404,redirect
from django.urls import reverse
from django.template.loader import get_template
import os
from xhtml2pdf import pisa

from List.models import Employee,Ta_Da

def index(request):

    if(request.method=="POST"):
        t_cost=0
        l_cost=0
        i_cost=0        
        date = request.POST["date"]
        name = request.POST["name"]
        t_cost = request.POST["t_cost"]
        l_cost = request.POST["l_cost"]
        i_cost = request.POST["i_cost"]
        tl_cost = float(t_cost)+ float(l_cost)+ float(i_cost)
        status = request.POST["status"]
        instance = Ta_Da(date=date,name=name,travel_cost=t_cost,lunch_cost=l_cost,instrument_cost=i_cost,total_cost=tl_cost,Paid=status)
        instance.save()
        return HttpResponseRedirect(reverse('List:show'))
    names = Employee.objects.all()
    diction ={'names':names}
    return render(request,'List/index.html',context=diction)

def show(request):
    tadas= Ta_Da.objects.all().order_by('-Paid','-date')

    diction ={'tadas':tadas}
    return render(request,'List/show.html',context=diction)

def change(request, pk):
    item = get_object_or_404(Ta_Da, pk=pk)
    item.Paid="paid"
    item.save()
    print(item)

    return redirect("List:show")

def render_pdf_view(request):
    tadas= Ta_Da.objects.all().order_by('-Paid','-date')
    template_path = 'List/pdf.html'
    context = {'tadas': tadas}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="TA_DA_List.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

Employee/templates/List/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Add TA/DA</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Horizontal form</h2>
  
  <form class="form-horizontal" action="/add" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label class="control-label col-sm-2" for="Date">Date:</label>
      <div class="col-sm-6">
        <input type="Date" class="form-control" id="date"  name="date" required>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2" for="name">Name:</label>
      <div class="col-sm-6">
        <select type="text" class="form-control" id="name"  name="name" required>
          <option value="">Select Name</option>
          {% for name in names %}
          <option value="{{name.name}}">{{name.name}}</option>
          {%endfor%}
        </select>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2" for="name">Travel cost:</label>
      <div class="col-sm-6">          
        <input type="text" class="form-control" id="t_cost" placeholder="Enter Travel cost" name="t_cost" required>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2" for="name">Lunch cost:</label>
      <div class="col-sm-6">          
        <input type="text" class="form-control" id="l_cost" placeholder="Enter Lunch cost" name="l_cost" required>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2" for="name">Instruments cost:</label>
      <div class="col-sm-6">          
        <input type="text" class="form-control" id="i_cost" placeholder="Enter Instruments cost" name="i_cost" required>
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2" for="name">Status:</label>
      <div class="col-sm-6">    
        <select type="text" class="form-control" id="status"  name="status" required>
          <option value="">Select Payment Status</option>
          
          <option value="paid">paid</option>
          <option value="unpaid">unpaid</option>
        </select>      
      </div>
    </div>
   
    <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-success">Submit</button>
      </div>
    </div>
  </form>
</div>

</body>
</html>

Employee/templates/List/pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>PDF </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <h2>TA/DA List</h2>
  
  <table class="table table-bordered">
    <tr>
      <th>Date</th>
      <th>Name</th>
      <th>Travel_cost</th>
      <th>Lunch_cost</th>
      <th>Instrument_cost</th>
      <th>Total_cost</th>
      <th>Payment Status</th>
    </tr>
    {% for data in tadas %}
    <tr>
      <td>{{ data.date }}</td>
      <td>{{ data.name }}</td>
      <td>{{ data.travel_cost }}</td>
      <td>{{ data.lunch_cost }}</td>
      <td>{{ data.instrument_cost }}</td>
      <td>{{ data.total_cost }}</td>
      <td>{{ data.Paid }} </td>
    </tr>
    {%endfor%}
  </table>
  

</div>

</body>
</html>

Employee/templates/List/show.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>TA/DA</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">

    <h2>TA/DA List</h2>
    
  
  <table class="table table-bordered">
    <tr>
      <th>Date</th>
      <th>Name</th>
      <th>Travel_cost</th>
      <th>Lunch_cost</th>
      <th>Instrument_cost</th>
      <th>Total_cost</th>
      <th>Payment Status</th>
    </tr>
    {% for data in tadas %}
    <tr>
      <td>{{ data.date }}</td>
      <td>{{ data.name }}</td>
      <td>{{ data.travel_cost }}</td>
      <td>{{ data.lunch_cost }}</td>
      <td>{{ data.instrument_cost }}</td>
      <td>{{ data.total_cost }}</td>
      <td>{{ data.Paid }} {% if data.Paid == "unpaid" %} <a  href="{% url 'List:change' pk=data.id %}" class="btn btn-success btn-sm">Change to paid</a>   {% endif %}      </td>
    </tr>
    {%endfor%}
  </table>
  <a  href="{% url 'List:add' %}" class="btn btn-info ">Add TA/DA</a>
  <a href="{% url 'List:pdf' %}"  class="btn btn-primary">Create PDF</a> 

</div>

</body>
</html>

Employee/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Horizontal form</h2>
  <form class="form-horizontal" action="">
    <div class="form-group">
      <label class="control-label col-sm-2" for="email">Email:</label>
      <div class="col-sm-10">
        <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2" for="pwd">Password:</label>
      <div class="col-sm-10">          
        <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pwd">
      </div>
    </div>
    <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <div class="checkbox">
          <label><input type="checkbox" name="remember"> Remember me</label>
        </div>
      </div>
    </div>
    <div class="form-group">        
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default">Submit</button>
      </div>
    </div>
  </form>
</div>

</body>
</html>